# Generated by Django 3.2.25 on 2024-03-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=200)),
                ('h_description', models.TextField()),
                ('h_contact', models.CharField(max_length=13)),
                ('h_specialities', models.IntegerField()),
                ('h_docotors', models.IntegerField()),
                ('viewed_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
