# Generated by Django 3.2.25 on 2024-03-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitals',
            old_name='h_docotors',
            new_name='h_doctors',
        ),
    ]
