# Generated by Django 3.2.25 on 2024-03-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_h_docotors_hospitals_h_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=200)),
                ('doc_spec', models.CharField(max_length=200)),
                ('doc_image', models.ImageField(upload_to='doctors')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_name', models.CharField(max_length=200)),
                ('pl_name', models.CharField(max_length=200)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_contact', models.CharField(max_length=10)),
                ('p_country', models.CharField(max_length=100)),
                ('p_state', models.CharField(max_length=100)),
                ('p_address', models.TextField()),
                ('p_purpose', models.TextField()),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departments')),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_name', models.CharField(max_length=200)),
                ('pl_name', models.CharField(max_length=200)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_contact', models.CharField(max_length=10)),
                ('p_country', models.CharField(max_length=100)),
                ('p_state', models.CharField(max_length=100)),
                ('p_address', models.TextField()),
                ('p_purpose', models.TextField()),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departments')),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctors')),
                ('h_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospitals')),
            ],
        ),
    ]
