# Generated by Django 3.2.25 on 2024-03-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='h_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.hospitals'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctors',
            name='dept_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.departments'),
        ),
    ]
