# Generated by Django 3.2.25 on 2024-03-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240307_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='h_image',
            field=models.ImageField(default=1, upload_to='hospitals'),
            preserve_default=False,
        ),
    ]
